"use client";

// Automated Case Documentation Auditor
//
// Every artifact a client or business vendor generates on the platform
// fires a typed event into recordCaseNoteEvent(). A template builds a
// DAP-format case note from the event payload — objective, factual,
// VR-documentation-standard — and persists it to localStorage. The
// counselor sees these notes on the client's /report and on the
// Business View dashboard.
//
// Notes are deterministic templates, not AI-generated, so they're
// reproducible at audit time and free to render.

// ─── Types ─────────────────────────────────────────────────────────────

export type ParticipantType =
  | "individual-client"
  | "business-vendor"
  | "employment-partner";

export type CaseNoteEventKind =
  // Module 1 — Self-Employment (individual client)
  | "concept-match-generated"
  | "business-plan-generated"
  // Module 2 — Self Advocacy (individual client)
  | "accommodation-letter-generated"
  | "problem-analysis-generated"
  | "eeoc-charge-generated"
  | "ocr-doj-complaint-generated"
  // Existing assessment / planning artifacts (individual client)
  | "interest-profiler-completed"
  | "tsa-completed"
  | "ipe-signed"
  | "resume-generated"
  // Business vendor / employer
  | "business-service-requested"
  | "business-service-approved"
  | "business-service-declined"
  | "business-service-released"
  // Employment Partner
  | "partner-opportunity-posted"
  | "partner-ce-selected"
  | "partner-ce-stage-advanced"
  | "partner-accommodation-inquiry"
  | "partner-placement-offered"
  | "partner-placement-accepted"
  | "partner-progress-update"
  | "partner-document-uploaded";

export interface CaseNote {
  id: string;
  // Subject
  participantType: ParticipantType;
  clientCaseId?: string;
  clientName?: string;
  businessOrgId?: string;
  businessOrgName?: string;
  partnerOrgId?: string;
  partnerOrgName?: string;
  // Metadata
  sessionAt: string;       // when the activity happened
  activityType: string;    // human-readable, e.g. "ADA Accommodation Draft"
  toolUsed: string;        // route or tool name
  eventKind: CaseNoteEventKind;
  // DAP body
  data: string;
  assessment: string;
  plan: string;
  // Provenance
  generatedAt: string;
  authorEmail?: string;    // for manual notes; null for auto-generated
  autoGenerated: boolean;
  sourceArtifactId?: string;
}

// ─── Storage ───────────────────────────────────────────────────────────

const KEY = "pathways-pro:case-notes-v1";

export function loadCaseNotes(): CaseNote[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(KEY);
    return raw ? (JSON.parse(raw) as CaseNote[]) : [];
  } catch {
    return [];
  }
}

export function saveCaseNotes(list: CaseNote[]) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(KEY, JSON.stringify(list));
}

export function appendCaseNote(note: CaseNote) {
  saveCaseNotes([note, ...loadCaseNotes()]);
}

export function notesForClient(caseId: string): CaseNote[] {
  return loadCaseNotes()
    .filter((n) => n.clientCaseId === caseId)
    .sort((a, b) => Date.parse(b.sessionAt) - Date.parse(a.sessionAt));
}

export function notesForBusinessOrg(orgId: string): CaseNote[] {
  return loadCaseNotes()
    .filter((n) => n.businessOrgId === orgId)
    .sort((a, b) => Date.parse(b.sessionAt) - Date.parse(a.sessionAt));
}

export function notesForPartnerOrg(orgId: string): CaseNote[] {
  return loadCaseNotes()
    .filter((n) => n.partnerOrgId === orgId)
    .sort((a, b) => Date.parse(b.sessionAt) - Date.parse(a.sessionAt));
}

export function notesForCounselor(emails: {
  clientCaseIds?: string[];
  businessOrgIds?: string[];
}): CaseNote[] {
  return loadCaseNotes()
    .filter(
      (n) =>
        (n.clientCaseId && emails.clientCaseIds?.includes(n.clientCaseId)) ||
        (n.businessOrgId && emails.businessOrgIds?.includes(n.businessOrgId)),
    )
    .sort((a, b) => Date.parse(b.sessionAt) - Date.parse(a.sessionAt));
}

function newId(): string {
  return "note-" + Math.random().toString(36).slice(2, 10);
}

// ─── Event types (discriminated union) ─────────────────────────────────

interface BaseClientEvent {
  participantType: "individual-client";
  caseId?: string;
  clientName: string;
  sessionAt?: string;
  sourceArtifactId?: string;
}
interface BaseBusinessEvent {
  participantType: "business-vendor";
  orgId: string;
  orgName: string;
  requesterName: string;
  sessionAt?: string;
  sourceArtifactId?: string;
}
interface BasePartnerEvent {
  participantType: "employment-partner";
  partnerOrgId: string;
  partnerOrgName: string;
  actorName: string;
  sessionAt?: string;
  sourceArtifactId?: string;
}

export type CaseNoteEvent =
  | (BaseClientEvent & {
      kind: "concept-match-generated";
      hollandCode?: string;
      conceptCount: number;
    })
  | (BaseClientEvent & {
      kind: "business-plan-generated";
      businessName: string;
      startingBudget: number;
      breakEvenMonth: number;
      atBudgetTotal: number;
    })
  | (BaseClientEvent & {
      kind: "accommodation-letter-generated";
      workplaceProblem: string;
      zeroCostCount: number;
      paidCount: number;
      totalPaidLow: number;
      totalPaidHigh: number;
      priceVerified: boolean;
    })
  | (BaseClientEvent & {
      kind: "problem-analysis-generated";
      employerName: string;
      incidentCount: number;
      statutesCited: number;
    })
  | (BaseClientEvent & {
      kind: "eeoc-charge-generated";
      employerName: string;
      bases: string[];
      earliestDate?: string;
      latestDate?: string;
    })
  | (BaseClientEvent & {
      kind: "ocr-doj-complaint-generated";
      agency: string;
      respondentName: string;
      rightsViolated: string[];
    })
  | (BaseClientEvent & {
      kind: "interest-profiler-completed";
      hollandCode: string;
    })
  | (BaseClientEvent & {
      kind: "tsa-completed";
      skillCount: number;
    })
  | (BaseClientEvent & {
      kind: "ipe-signed";
      vocationalGoal: string;
    })
  | (BaseClientEvent & {
      kind: "resume-generated";
      targetJob: string;
    })
  | (BaseBusinessEvent & {
      kind: "business-service-requested";
      serviceTitle: string;
      matterCaption?: string;
      subjectClientName?: string;
      urgency: string;
      notes: string;
      scopeRole: string;
    })
  | (BaseBusinessEvent & {
      kind: "business-service-approved";
      serviceTitle: string;
      decisionedByEmail: string;
    })
  | (BaseBusinessEvent & {
      kind: "business-service-declined";
      serviceTitle: string;
      decisionedByEmail: string;
      reason: string;
    })
  | (BaseBusinessEvent & {
      kind: "business-service-released";
      serviceTitle: string;
      releasedByEmail: string;
    })
  | (BasePartnerEvent & {
      kind: "partner-opportunity-posted";
      opportunityTitle: string;
      opportunityKind: string;
      hoursPerWeek: number;
    })
  | (BasePartnerEvent & {
      kind: "partner-ce-selected";
      acknowledgedAt?: string;
    })
  | (BasePartnerEvent & {
      kind: "partner-ce-stage-advanced";
      clientName?: string;
      caseId?: string;
      newStage: string;
    })
  | (BasePartnerEvent & {
      kind: "partner-accommodation-inquiry";
      jobTitle: string;
      question: string;
    })
  | (BasePartnerEvent & {
      kind: "partner-placement-offered";
      clientName: string;
      caseId: string;
      opportunityTitle: string;
    })
  | (BasePartnerEvent & {
      kind: "partner-placement-accepted";
      clientName: string;
      caseId: string;
      opportunityTitle: string;
    })
  | (BasePartnerEvent & {
      kind: "partner-progress-update";
      clientName: string;
      caseId: string;
      hoursWorked: number;
      reportingWeek: string;
      flags: string[];
    })
  | (BasePartnerEvent & {
      kind: "partner-document-uploaded";
      documentTitle: string;
      documentKind: string;
    });

// ─── recordCaseNoteEvent ───────────────────────────────────────────────

export function recordCaseNoteEvent(event: CaseNoteEvent) {
  const sessionAt = event.sessionAt ?? new Date().toISOString();
  const note: CaseNote = {
    id: newId(),
    participantType: event.participantType,
    sessionAt,
    generatedAt: new Date().toISOString(),
    autoGenerated: true,
    eventKind: event.kind,
    sourceArtifactId: event.sourceArtifactId,
    activityType: activityLabel(event.kind),
    toolUsed: toolRoute(event.kind),
    ...(event.participantType === "individual-client"
      ? {
          clientCaseId: event.caseId,
          clientName: event.clientName,
        }
      : event.participantType === "business-vendor"
        ? {
            businessOrgId: event.orgId,
            businessOrgName: event.orgName,
            clientName: event.requesterName,
          }
        : {
            partnerOrgId: event.partnerOrgId,
            partnerOrgName: event.partnerOrgName,
            clientName: event.actorName,
            // If the partner event references a linked client case
            clientCaseId:
              "caseId" in event ? event.caseId : undefined,
          }),
    ...buildDap(event),
  };
  appendCaseNote(note);
  return note;
}

function activityLabel(k: CaseNoteEventKind): string {
  return {
    "concept-match-generated": "Business Concept Matching",
    "business-plan-generated": "Business Plan Generation",
    "accommodation-letter-generated": "ADA Accommodation Letter Draft",
    "problem-analysis-generated": "Discrimination Documentation — Problem Analysis Report",
    "eeoc-charge-generated": "EEOC Charge of Discrimination — Particulars Draft",
    "ocr-doj-complaint-generated": "OCR / DOJ Civil Rights Complaint Draft",
    "interest-profiler-completed": "Interest Profiler — Mini-IPIP + RIASEC",
    "tsa-completed": "Transferable Skills Analysis",
    "ipe-signed": "IPE Execution",
    "resume-generated": "Targeted Resume Generation",
    "business-service-requested": "Business Service Request — Submission",
    "business-service-approved": "Business Service Request — Counselor Approval",
    "business-service-declined": "Business Service Request — Counselor Decline",
    "business-service-released": "Business Service Deliverable — Counselor Release",
    "partner-opportunity-posted": "Employment Partner — Opportunity Posted",
    "partner-ce-selected": "Employment Partner — Customized Employment Selected",
    "partner-ce-stage-advanced": "Customized Employment — Stage Advanced",
    "partner-accommodation-inquiry": "Employment Partner — Accommodation Inquiry",
    "partner-placement-offered": "Employment Partner — Placement Offered",
    "partner-placement-accepted": "Employment Partner — Placement Accepted",
    "partner-progress-update": "Employment Partner — Weekly Progress Update",
    "partner-document-uploaded": "Employment Partner — Document Upload",
  }[k];
}

function toolRoute(k: CaseNoteEventKind): string {
  return {
    "concept-match-generated": "/entrepreneurship/concept-match",
    "business-plan-generated": "/entrepreneurship/business-plan",
    "accommodation-letter-generated": "/accommodation-letter",
    "problem-analysis-generated": "/self-advocacy/incident-report",
    "eeoc-charge-generated": "/self-advocacy/eeoc",
    "ocr-doj-complaint-generated": "/self-advocacy/ocr-doj",
    "interest-profiler-completed": "/assessment",
    "tsa-completed": "/transferable-skills",
    "ipe-signed": "/ipe",
    "resume-generated": "/resume",
    "business-service-requested": "/business-portal/services",
    "business-service-approved": "/dashboard/business",
    "business-service-declined": "/dashboard/business",
    "business-service-released": "/dashboard/business",
    "partner-opportunity-posted": "/partner-portal/opportunities",
    "partner-ce-selected": "/partner-portal/customized-employment",
    "partner-ce-stage-advanced": "/partner-portal/customized-employment",
    "partner-accommodation-inquiry": "/partner-portal/accommodation-requests",
    "partner-placement-offered": "/partner-portal/opportunities",
    "partner-placement-accepted": "/partner-portal/opportunities",
    "partner-progress-update": "/partner-portal",
    "partner-document-uploaded": "/partner-portal",
  }[k];
}

// ─── DAP templates (deterministic) ─────────────────────────────────────

function buildDap(e: CaseNoteEvent): {
  data: string;
  assessment: string;
  plan: string;
} {
  switch (e.kind) {
    case "concept-match-generated":
      return {
        data: `The client engaged the Pathways Pro Business Concept Matchmaker, generating ${e.conceptCount} tailored business-concept recommendations${e.hollandCode ? ` synthesized from their Holland code (${e.hollandCode})` : ""}, transferable skills, vocational goal, and any reported accommodation context. Each concept includes startup cost projections, accommodation considerations, dedicated assistive-technology budget items, and risk profile.`,
        assessment: `Client engaged in a guided business feasibility exercise exploring self-employment pathways consistent with their vocational strengths and accommodation needs. The activity advances feasibility assessment under WIOA Title IV self-employment outcome criteria and reflects appropriate use of the platform's matchmaking tools.`,
        plan: `Client to discuss the matched concepts with assigned VR Counselor at the next scheduled session and select one concept to develop into a full business plan. Counselor to evaluate alignment with the active IPE vocational goal and assess whether self-employment should be incorporated into the IPE.`,
      };

    case "business-plan-generated":
      return {
        data: `The client utilized the platform to generate a complete VR-fundable business plan for "${e.businessName}" with a $${e.startingBudget.toLocaleString()} starting budget. The plan includes executive summary, target-market analysis with competitor landscape and go-to-market channels, operations workflow with accommodations built into the design, 30/60/90-day milestones, financial projections with break-even projected at month ${e.breakEvenMonth}, a dedicated assistive-technology budget totaling $${e.atBudgetTotal.toLocaleString()}, risk/mitigation analysis, and identified funding pathways.`,
        assessment: `Client engaged in a guided business feasibility exercise for their proposed venture, demonstrating measurable progress toward business plan readiness and financial viability mapping. The activity supports the documentation requirements of state VR self-employment review standards.`,
        plan: `Client to submit the generated plan to assigned VR Counselor for state VR self-employment review and to a SCORE chapter or Small Business Development Center mentor for operator-level feedback. Counselor to evaluate plan for inclusion in the active IPE as a self-employment vocational goal and to coordinate assistive-technology service authorizations as appropriate.`,
      };

    case "accommodation-letter-generated":
      return {
        data: `The client utilized the platform to draft a formal ADA Title I Reasonable Accommodation request letter addressing the workplace barrier: "${e.workplaceProblem}." The letter identified ${e.zeroCostCount} zero-cost / administrative solutions and ${e.paidCount} paid solutions with an estimated total cost range of $${e.totalPaidLow.toLocaleString()}–$${e.totalPaidHigh.toLocaleString()}.${e.priceVerified ? " Pricing was live-verified via retail search at the time of generation." : " Pricing reflects AI-estimated retail ranges."} The letter pre-empts the undue-hardship defense by presenting both cost columns alongside Job Accommodation Network (JAN) data.`,
        assessment: `The activity demonstrates the client's active engagement in self-advocacy and exercise of their rights under the ADA. The generated letter enhances the client's readiness to initiate the interactive process with their employer and reflects appropriate use of the platform's legal-tech tools for non-confrontational rights enforcement.`,
        plan: `Client to review the generated letter with assigned VR Counselor and submit to HR upon counselor concurrence. Counselor to verify alignment with state VR self-advocacy guidelines, document the date of submission, and monitor for any retaliatory action affecting the active IPE.`,
      };

    case "problem-analysis-generated":
      return {
        data: `The client utilized the platform to compile a Problem Analysis Report documenting ${e.incidentCount} discrete incident${e.incidentCount === 1 ? "" : "s"} of alleged workplace discrimination by ${e.employerName}. The report includes a chronological incident log, employer information, executive summary, pattern analysis, and a legal cross-reference identifying ${e.statutesCited} federal statute${e.statutesCited === 1 ? "" : "s"} potentially implicated.`,
        assessment: `Client took proactive steps to document a barrier to employment and preserve evidence for potential civil-rights enforcement. The activity reflects appropriate self-advocacy and case-preparation behaviors and advances the client's readiness for engagement with the EEOC, an employment-law attorney, or the state Protection & Advocacy (P&A) agency.`,
        plan: `Client to review the Problem Analysis Report with VR Counselor and a licensed attorney before any formal filing. Counselor to coordinate referral to the state P&A agency for free legal screening and to document any retaliation impacts on the active IPE.`,
      };

    case "eeoc-charge-generated":
      return {
        data: `The client utilized the platform to draft the Particulars section of an EEOC Charge of Discrimination against ${e.employerName} based on the following protected basis or bases: ${e.bases.join(", ")}. The earliest documented incident was ${e.earliestDate || "unspecified"}; the most recent was ${e.latestDate || "unspecified"}. The drafted charge cites the applicable statutory bases and outlines the prima facie elements the EEOC investigator will assess.`,
        assessment: `The client demonstrated competency in exercising federal employment-discrimination protections. The activity supports continued progress toward securing redress under the cited statutes and maintains the 180/300-day filing window required for charge submission.`,
        plan: `Client to review the draft charge with VR Counselor and a licensed employment-law attorney before submission via publicportal.eeoc.gov. Counselor to provide a warm referral to legal services and to monitor potential retaliation impacts on the active IPE.`,
      };

    case "ocr-doj-complaint-generated":
      return {
        data: `The client utilized the platform to draft a civil rights complaint to ${e.agency} against ${e.respondentName} alleging violation of: ${e.rightsViolated.join(", ")}. The drafted complaint includes formal allegations, the statutory legal basis, and remedies sought.`,
        assessment: `Client took proactive steps to enforce non-employment civil-rights protections under the cited statutes. The activity advances readiness for agency-level enforcement action and reflects appropriate use of the platform's legal-advocacy tools.`,
        plan: `Client to review the draft complaint with VR Counselor and appropriate legal counsel before submission. Counselor to confirm respondent type and appropriate filing pathway, document the submission, and monitor for retaliation impacts on the active case.`,
      };

    case "interest-profiler-completed":
      return {
        data: `The client completed the Pathways Pro Interest Profiler (Mini-IPIP Big Five + O*NET RIASEC short form), yielding a Holland code of ${e.hollandCode}. Results were synced to the shared client report and used to drive the labor-market analysis and occupational-match ranking on the platform.`,
        assessment: `Client engaged in a validated interest assessment, demonstrating active participation in the vocational evaluation phase of the rehabilitation process. The completed profile advances readiness for occupational exploration and IPE goal-setting.`,
        plan: `Counselor to review the Holland code with the client at the next scheduled session, contrast it with the client's stated vocational goal on file, and integrate the findings into the active IPE evaluation criteria.`,
      };

    case "tsa-completed":
      return {
        data: `The client completed a Transferable Skills Analysis on the platform, identifying ${e.skillCount} discrete transferable skill${e.skillCount === 1 ? "" : "s"} from prior paid work, volunteer experience, caregiving, and/or hobbies. Results were synced to the shared client report.`,
        assessment: `Client engaged in a structured TSA exercise, demonstrating progress toward employability assessment and goal-setting. The activity supports the WIOA Title IV requirement to identify the client's strengths, resources, priorities, and abilities as a basis for the IPE.`,
        plan: `Counselor to review the TSA results with the client, cross-reference the identified skills against the active IPE vocational goal, and update the IPE evidence base as appropriate.`,
      };

    case "ipe-signed":
      return {
        data: `The Individualized Plan for Employment was executed on the platform. Vocational goal of record: ${e.vocationalGoal}. Counselor and client signature blocks captured with timestamp and originating IP per E-SIGN Act § 7001.`,
        assessment: `IPE execution is a required milestone under WIOA Title IV § 102(b). The signed document establishes the agency's authorized scope of services and the client's mutually-agreed responsibilities.`,
        plan: `Counselor to authorize agreed services per the executed plan and to schedule the first quarterly progress review. Client to begin executing agreed responsibilities and report any change in circumstances promptly.`,
      };

    case "resume-generated":
      return {
        data: `The client used the platform's targeted resume generator to draft a one-page resume (and matching cover letter when company / hiring manager were provided) for the target position of ${e.targetJob}. Generation drew on the client's intake, assessment, and TSA data.`,
        assessment: `Activity supports employment readiness and active job-search execution. Drafted artifact enhances the client's competitiveness for the targeted role.`,
        plan: `Counselor to review the generated documents for accuracy, advise on personalization, and confirm the client's job-search plan for the targeting employer.`,
      };

    case "business-service-requested":
      return {
        data: `${e.requesterName} (${e.scopeRole}) at ${e.orgName} submitted a service request for "${e.serviceTitle}"${e.matterCaption ? ` regarding the matter "${e.matterCaption}"` : ""}${e.subjectClientName ? ` concerning ${e.subjectClientName}` : ""}. Urgency: ${e.urgency}. Requester notes: "${e.notes || "—"}". The request entered the counselor's pre-release review queue with status pending-counselor-review.`,
        assessment: `Vendor utilized the platform service catalog to initiate a counselor-supervised engagement, reflecting appropriate use of the pre-release review workflow. The request supports continued collaboration consistent with VR third-party agreement standards and preserves the PHI boundary between business and clinical surfaces.`,
        plan: `Assigned VR Counselor to review the request, confirm alignment with the authorized scope of the referral agreement or active IPE, and either approve to begin engagement or decline with documented reason. Outcome reflected on the shared activity feed visible to the requesting vendor.`,
      };

    case "business-service-approved":
      return {
        data: `VR Counselor ${e.decisionedByEmail} approved the service request for "${e.serviceTitle}" submitted by ${e.orgName}. Status transitioned from pending-counselor-review to approved-in-progress.`,
        assessment: `Approval indicates the requested service aligns with the authorized scope of the active referral / IPE. The action maintains the auditable pre-release review chain and preserves the PHI boundary between business-side and clinical surfaces of the platform.`,
        plan: `Engagement team to produce the draft deliverable per service-level expectations. Counselor to review draft prior to release and to coordinate with the requesting vendor on any clarifying questions.`,
      };

    case "business-service-declined":
      return {
        data: `VR Counselor ${e.decisionedByEmail} declined the service request for "${e.serviceTitle}" submitted by ${e.orgName}. Documented reason: "${e.reason}". Status transitioned to declined.`,
        assessment: `Decline reflects appropriate gatekeeping of the counselor-supervised review workflow and protection of the authorized scope of services. Decision communicated transparently to the requesting vendor via the shared activity feed.`,
        plan: `Counselor to follow up with the requesting vendor with any alternative service routing as appropriate. No further action required unless vendor resubmits a modified request.`,
      };

    case "business-service-released":
      return {
        data: `VR Counselor ${e.releasedByEmail} released the deliverable for service "${e.serviceTitle}" to ${e.orgName} following pre-release review. The deliverable became visible in the business client's vault at the time of release.`,
        assessment: `Release reflects completion of the counselor's pre-release review process, confirming the deliverable meets the documentation, accuracy, and PHI-boundary standards required before disclosure to a business-side recipient.`,
        plan: `Counselor to document the release in the case file, monitor the activity feed for acknowledgment by the requesting org, and follow up if no acknowledgment is recorded within five business days.`,
      };

    case "partner-opportunity-posted":
      return {
        data: `${e.actorName} of ${e.partnerOrgName} posted an opportunity titled "${e.opportunityTitle}" categorized as ${e.opportunityKind.replaceAll("-", " ")}, with a workload of ${e.hoursPerWeek} hours per week. The posting is visible to the counselor for candidate matching.`,
        assessment: `Activity reflects continued participation of the employment partner in the platform's competitive integrated employment pipeline. Posting expands available placement options for clients on the counselor's caseload.`,
        plan: `Counselor to review the posting for fit against the active caseload, identify candidate matches with appropriate vocational profile, and coordinate referral discussions with the partner.`,
      };

    case "partner-ce-selected":
      return {
        data: `${e.partnerOrgName} elected to participate in Customized Employment services on the platform. The Customized Employment workspace is now available in the partner's portal and visible in the counselor's per-partner case file.`,
        assessment: `Selection signals the partner's willingness to engage in strengths-based, individualized job design — an evidence-based pathway for clients with significant disabilities who benefit from carved roles, negotiated work conditions, or self-employment models.`,
        plan: `Counselor to schedule a Customized Employment intake conversation with the partner, identify candidates from the active caseload who may benefit, and initiate Discovery on at least one match within the next 30 days.`,
      };

    case "partner-ce-stage-advanced":
      return {
        data: `Customized Employment engagement at ${e.partnerOrgName}${e.clientName ? ` for client ${e.clientName}` : ""} advanced to the "${e.newStage.replaceAll("-", " ")}" stage. The stage transition was logged by ${e.actorName}.`,
        assessment: `Stage advancement reflects measurable progress on the Customized Employment continuum (Discovery → Job Design → Employer Negotiation → Worksite Customization → Placement → Stabilization → Long-term Support). Movement supports the WIOA § 7(38) competitive integrated employment outcome standard.`,
        plan: `Counselor and partner to schedule the planning conversation appropriate to the new stage, document evidence supporting the transition, and confirm next milestone target date.`,
      };

    case "partner-accommodation-inquiry":
      return {
        data: `${e.actorName} of ${e.partnerOrgName} submitted an accommodation inquiry regarding the position "${e.jobTitle}": "${e.question.slice(0, 240)}${e.question.length > 240 ? "…" : ""}"`,
        assessment: `Inquiry demonstrates the partner's good-faith engagement in the ADA interactive process and willingness to design accommodations proactively. Activity supports the platform's compliance-by-default posture and reduces downstream EEO risk for the partner.`,
        plan: `Counselor to respond to the inquiry within two business days, recommend an accommodation grounded in JAN standard practices, and route any cost-bearing requests through the appropriate VR service authorization channel.`,
      };

    case "partner-placement-offered":
      return {
        data: `${e.partnerOrgName} extended an employment offer to ${e.clientName} (Case ${e.caseId}) for the position "${e.opportunityTitle}". Offer was generated through the platform's matching and is visible in both the counselor and client case files.`,
        assessment: `Offer reflects successful matching of vocational interests, accommodations, and partner capacity. Acceptance would advance the active IPE toward the competitive integrated employment outcome required under WIOA Title IV.`,
        plan: `Counselor to discuss offer terms with the client at the next session, confirm accommodation readiness with the partner, and document the client's decision on the IPE. Job-coaching service authorization to be opened upon acceptance.`,
      };

    case "partner-placement-accepted":
      return {
        data: `${e.clientName} (Case ${e.caseId}) accepted the placement offer from ${e.partnerOrgName} for the position "${e.opportunityTitle}". Placement workspace is now active for tracking 30 / 60 / 90-day retention milestones.`,
        assessment: `Acceptance triggers the WIOA § 116 common performance indicator tracking window. Successful retention through Day 90 contributes to the agency's competitive integrated employment outcome reporting.`,
        plan: `Counselor to authorize any agreed-upon job-coaching or assistive-technology services, schedule Day-30 check-in with both the partner and the client, and document baseline accommodations in place at start of employment.`,
      };

    case "partner-progress-update":
      return {
        data: `${e.actorName} of ${e.partnerOrgName} submitted a weekly progress update for ${e.clientName} (Case ${e.caseId}) covering reporting week ${e.reportingWeek}. Hours worked: ${e.hoursWorked}.${e.flags.length > 0 ? ` Flags raised: ${e.flags.join(", ")}.` : ""}`,
        assessment: `Routine progress reporting maintains the platform's auditable engagement trail and surfaces early indicators of retention risk. ${e.flags.length > 0 ? "Flagged concerns warrant counselor follow-up before the next reporting cycle." : "No flags raised this reporting period."}`,
        plan: `Counselor to review the update, contact the client to confirm self-reported status, and ${e.flags.length > 0 ? "respond to the flagged concerns within the next two business days." : "continue routine monitoring."}`,
      };

    case "partner-document-uploaded":
      return {
        data: `${e.actorName} of ${e.partnerOrgName} uploaded a document titled "${e.documentTitle}" categorized as ${e.documentKind}. The document is now available in the counselor's per-partner case file.`,
        assessment: `Upload supports documentation completeness for the partner case file and contributes to the platform's auditable engagement record for state VR program review.`,
        plan: `Counselor to review the uploaded document, file under the appropriate case categorization, and acknowledge receipt to the partner.`,
      };
  }
}
