"use client";

import { useMemo, useState } from "react";
import { appendManualCaseNote, type CaseNote, type ManualNoteScope } from "@/lib/case-notes";

interface Props {
  notes: CaseNote[];
  emptyLabel?: string;
  title?: string;
  // When `scope` + `counselorEmail` are supplied, the panel shows an
  // "Add case note" button + inline DAP form. On save we append a
  // manual case note and call onAdded so the parent can refresh.
  scope?: ManualNoteScope;
  counselorEmail?: string;
  onAdded?: () => void;
}

// Renders a vertical, scannable case-note feed with DAP body collapsed
// by default. Used on the counselor's client /report view and on the
// Business View dashboard.
export function CaseNotesPanel({
  notes,
  emptyLabel = "No case notes generated yet.",
  title = "Case Notes",
  scope,
  counselorEmail,
  onAdded,
}: Props) {
  const [expanded, setExpanded] = useState<Set<string>>(
    new Set(notes.slice(0, 1).map((n) => n.id)),
  );
  const [adding, setAdding] = useState(false);

  const grouped = useMemo(() => groupByDate(notes), [notes]);
  const canAdd = Boolean(scope && counselorEmail);

  function toggle(id: string) {
    setExpanded((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function handleSaved(noteId: string) {
    setAdding(false);
    setExpanded((prev) => new Set(prev).add(noteId));
    onAdded?.();
  }

  return (
    <section aria-label={title} className="print:hidden">
      <div className="flex items-baseline justify-between gap-3 flex-wrap mb-3">
        {title && <h2 className="text-2xl">{title}</h2>}
        <div className="flex items-baseline gap-3 ml-auto">
          {notes.length > 0 && (
            <span className="text-xs uppercase tracking-wider text-ink/55">
              {notes.length} note{notes.length === 1 ? "" : "s"}
            </span>
          )}
          {canAdd && !adding && (
            <button
              onClick={() => setAdding(true)}
              className="grad-tealblue text-white text-xs font-semibold px-3 py-1.5 rounded-md"
            >
              + Add case note
            </button>
          )}
        </div>
      </div>

      {canAdd && adding && (
        <AddCaseNoteForm
          scope={scope!}
          counselorEmail={counselorEmail!}
          onCancel={() => setAdding(false)}
          onSaved={handleSaved}
        />
      )}

      {notes.length === 0 ? (
        <div className="border border-dashed border-ink/20 rounded-lg p-6 text-center text-ink/55">
          {emptyLabel}
        </div>
      ) : (
        <div className="space-y-5">
          {Object.entries(grouped).map(([date, dayNotes]) => (
            <div key={date}>
              <h3 className="text-xs uppercase tracking-widest text-accent font-semibold mb-2">
                {date}
              </h3>
              <ol className="space-y-2" role="list">
                {dayNotes.map((n) => (
                  <li
                    key={n.id}
                    className={`border-l-4 bg-cream rounded-r-lg ${
                      n.autoGenerated
                        ? "border-accent/50"
                        : "border-emerald-500"
                    }`}
                  >
                    <button
                      onClick={() => toggle(n.id)}
                      aria-expanded={expanded.has(n.id)}
                      className="w-full text-left p-4 hover:bg-accent/5"
                    >
                      <div className="flex items-baseline justify-between gap-3 flex-wrap">
                        <div className="font-semibold flex items-baseline gap-2">
                          {n.activityType}
                          {!n.autoGenerated && (
                            <span className="text-[9px] uppercase tracking-wider bg-emerald-100 text-emerald-900 px-1.5 py-0.5 rounded-full font-semibold">
                              Counselor
                            </span>
                          )}
                        </div>
                        <div className="text-xs text-ink/55">
                          {new Date(n.sessionAt).toLocaleString()}
                        </div>
                      </div>
                      <div className="text-xs text-ink/60 mt-0.5">
                        {participantBadge(n)} · tool: {n.toolUsed}
                      </div>
                    </button>
                    {expanded.has(n.id) && (
                      <div className="px-4 pb-4 space-y-2 text-sm">
                        <DapBlock label="Data" body={n.data} />
                        <DapBlock label="Assessment" body={n.assessment} />
                        <DapBlock label="Plan" body={n.plan} />
                        <div className="text-[11px] text-ink/55 italic pt-1">
                          {n.autoGenerated
                            ? "Auto-generated by Pathways Pro Documentation Auditor"
                            : `Authored by ${n.authorEmail}`}{" "}
                          on {new Date(n.generatedAt).toLocaleString()}
                        </div>
                      </div>
                    )}
                  </li>
                ))}
              </ol>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

function AddCaseNoteForm({
  scope,
  counselorEmail,
  onCancel,
  onSaved,
}: {
  scope: ManualNoteScope;
  counselorEmail: string;
  onCancel: () => void;
  onSaved: (noteId: string) => void;
}) {
  const [activityType, setActivityType] = useState("");
  const [data, setData] = useState("");
  const [assessment, setAssessment] = useState("");
  const [plan, setPlan] = useState("");
  const [sessionAt, setSessionAt] = useState(() => {
    // Format current time for datetime-local input
    const d = new Date();
    d.setMinutes(d.getMinutes() - d.getTimezoneOffset());
    return d.toISOString().slice(0, 16);
  });
  const [busy, setBusy] = useState(false);

  function save() {
    if (!activityType.trim() || !data.trim()) return;
    setBusy(true);
    const note = appendManualCaseNote({
      scope,
      authorEmail: counselorEmail,
      activityType: activityType.trim(),
      data: data.trim(),
      assessment: assessment.trim() || "—",
      plan: plan.trim() || "—",
      sessionAt: new Date(sessionAt).toISOString(),
    });
    onSaved(note.id);
  }

  return (
    <div className="border-l-4 border-emerald-500 bg-emerald-50/30 rounded-r-lg p-4 mb-4 space-y-3">
      <div className="flex items-baseline justify-between gap-3">
        <h3 className="font-semibold text-sm">
          New case note ·{" "}
          <span className="text-ink/55 font-normal">
            {scope.kind === "client"
              ? `Client ${scope.clientName}`
              : `${scope.kind === "business" ? "Business" : scope.kind === "vendor" ? "Vendor" : "Partner"} · ${scope.orgName}`}
          </span>
        </h3>
        <button
          onClick={onCancel}
          className="text-xs text-ink/55 hover:text-ink"
        >
          Cancel
        </button>
      </div>
      <div className="grid sm:grid-cols-2 gap-3">
        <Field label="Activity type *">
          <input
            value={activityType}
            onChange={(e) => setActivityType(e.target.value)}
            placeholder="e.g., Phone call with HR director"
            className="w-full bg-white border border-ink/15 rounded-md px-3 py-1.5 text-sm"
            autoFocus
          />
        </Field>
        <Field label="When">
          <input
            type="datetime-local"
            value={sessionAt}
            onChange={(e) => setSessionAt(e.target.value)}
            className="w-full bg-white border border-ink/15 rounded-md px-3 py-1.5 text-sm"
          />
        </Field>
      </div>
      <Field label="Data (what happened — objective facts) *">
        <textarea
          value={data}
          onChange={(e) => setData(e.target.value)}
          rows={3}
          placeholder="What was observed, said, or done in this contact."
          className="w-full bg-white border border-ink/15 rounded-md px-3 py-2 text-sm"
        />
      </Field>
      <Field label="Assessment (interpretation / clinical impression)">
        <textarea
          value={assessment}
          onChange={(e) => setAssessment(e.target.value)}
          rows={2}
          placeholder="Counselor's interpretation of what the data means."
          className="w-full bg-white border border-ink/15 rounded-md px-3 py-2 text-sm"
        />
      </Field>
      <Field label="Plan (next step / commitment)">
        <textarea
          value={plan}
          onChange={(e) => setPlan(e.target.value)}
          rows={2}
          placeholder="What you or the client will do next, by when."
          className="w-full bg-white border border-ink/15 rounded-md px-3 py-2 text-sm"
        />
      </Field>
      <div className="flex gap-2 items-baseline">
        <button
          onClick={save}
          disabled={busy || !activityType.trim() || !data.trim()}
          className="grad-tealblue text-white font-semibold text-sm px-4 py-2 rounded-md disabled:opacity-50"
        >
          {busy ? "Saving…" : "Save case note"}
        </button>
        <span className="text-xs text-ink/55">
          Signed by {counselorEmail}
        </span>
      </div>
    </div>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <label className="block">
      <span className="block text-[10px] uppercase tracking-wider text-ink/55 mb-1">
        {label}
      </span>
      {children}
    </label>
  );
}

function DapBlock({ label, body }: { label: string; body: string }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-wider text-accent font-bold">
        {label}
      </div>
      <p className="text-ink/85 leading-snug whitespace-pre-wrap">{body}</p>
    </div>
  );
}

function participantBadge(n: CaseNote): string {
  if (n.participantType === "individual-client") {
    return `Client · ${n.clientName ?? "—"}${n.clientCaseId ? ` (${n.clientCaseId})` : ""}`;
  }
  if (n.participantType === "employment-partner") {
    return `Partner · ${n.partnerOrgName ?? "—"}`;
  }
  return `${n.businessOrgName ?? "—"}${n.clientName ? ` (${n.clientName})` : ""}`;
}

function groupByDate(notes: CaseNote[]): Record<string, CaseNote[]> {
  const out: Record<string, CaseNote[]> = {};
  for (const n of notes) {
    const d = new Date(n.sessionAt);
    const key = d.toLocaleDateString(undefined, {
      weekday: "short",
      year: "numeric",
      month: "short",
      day: "numeric",
    });
    (out[key] ||= []).push(n);
  }
  return out;
}
