"use client";

import { useMemo, useState } from "react";
import type { CaseNote } from "@/lib/case-notes";

interface Props {
  notes: CaseNote[];
  emptyLabel?: string;
  title?: string;
}

// Renders a vertical, scannable case-note feed with DAP body collapsed
// by default. Used on the counselor's client /report view and on the
// Business View dashboard.
export function CaseNotesPanel({
  notes,
  emptyLabel = "No case notes generated yet.",
  title = "Case Notes",
}: Props) {
  const [expanded, setExpanded] = useState<Set<string>>(
    new Set(notes.slice(0, 1).map((n) => n.id)),
  );

  const grouped = useMemo(() => groupByDate(notes), [notes]);

  function toggle(id: string) {
    setExpanded((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  if (notes.length === 0) {
    return (
      <section aria-label={title}>
        <h2 className="text-2xl mb-2">{title}</h2>
        <div className="border border-dashed border-ink/20 rounded-lg p-6 text-center text-ink/55">
          {emptyLabel}
        </div>
      </section>
    );
  }

  return (
    <section aria-label={title} className="print:hidden">
      <div className="flex items-baseline justify-between gap-3 flex-wrap mb-3">
        <h2 className="text-2xl">{title}</h2>
        <span className="text-xs uppercase tracking-wider text-ink/55">
          {notes.length} note{notes.length === 1 ? "" : "s"} ·
          auto-generated · DAP format
        </span>
      </div>
      <div className="space-y-5">
        {Object.entries(grouped).map(([date, dayNotes]) => (
          <div key={date}>
            <h3 className="text-xs uppercase tracking-widest text-accent font-semibold mb-2">
              {date}
            </h3>
            <ol className="space-y-2" role="list">
              {dayNotes.map((n) => (
                <li
                  key={n.id}
                  className="border-l-4 border-accent/50 bg-cream rounded-r-lg"
                >
                  <button
                    onClick={() => toggle(n.id)}
                    aria-expanded={expanded.has(n.id)}
                    className="w-full text-left p-4 hover:bg-accent/5"
                  >
                    <div className="flex items-baseline justify-between gap-3 flex-wrap">
                      <div className="font-semibold">{n.activityType}</div>
                      <div className="text-xs text-ink/55">
                        {new Date(n.sessionAt).toLocaleString()}
                      </div>
                    </div>
                    <div className="text-xs text-ink/60 mt-0.5">
                      {participantBadge(n)} · tool: {n.toolUsed}
                    </div>
                  </button>
                  {expanded.has(n.id) && (
                    <div className="px-4 pb-4 space-y-2 text-sm">
                      <DapBlock label="Data" body={n.data} />
                      <DapBlock label="Assessment" body={n.assessment} />
                      <DapBlock label="Plan" body={n.plan} />
                      <div className="text-[11px] text-ink/55 italic pt-1">
                        {n.autoGenerated
                          ? "Auto-generated by Pathways Pro Documentation Auditor"
                          : `Authored by ${n.authorEmail}`}{" "}
                        on {new Date(n.generatedAt).toLocaleString()}
                      </div>
                    </div>
                  )}
                </li>
              ))}
            </ol>
          </div>
        ))}
      </div>
    </section>
  );
}

function DapBlock({ label, body }: { label: string; body: string }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-wider text-accent font-bold">
        {label}
      </div>
      <p className="text-ink/85 leading-snug">{body}</p>
    </div>
  );
}

function participantBadge(n: CaseNote): string {
  if (n.participantType === "individual-client") {
    return `Client · ${n.clientName ?? "—"}${n.clientCaseId ? ` (${n.clientCaseId})` : ""}`;
  }
  return `Business · ${n.businessOrgName ?? "—"}${n.clientName ? ` (${n.clientName})` : ""}`;
}

function groupByDate(notes: CaseNote[]): Record<string, CaseNote[]> {
  const out: Record<string, CaseNote[]> = {};
  for (const n of notes) {
    const d = new Date(n.sessionAt);
    const key = d.toLocaleDateString(undefined, {
      weekday: "short",
      year: "numeric",
      month: "short",
      day: "numeric",
    });
    (out[key] ||= []).push(n);
  }
  return out;
}
